# GraphQL Query (.gql variant)
query GetUserWithPosts($id: ID!, $limit: Int = 5) {
  user(id: $id) {
    id
    name
    email
    role
    posts(limit: $limit) {
      id
      title
      published
      createdAt
    }
  }
}

mutation CreatePost($input: CreatePostInput!) {
  createPost(input: $input) {
    id
    title
    published
  }
}

fragment UserFields on User {
  id
  name
  email
}

subscription OnPostPublished {
  postPublished {
    id
    title
    author {
      ...UserFields
    }
  }
}
